trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  node_version: '20.x'

steps:
  - task: UseNode@1
    inputs:
      version: $(node_version)
    displayName: 'Use Node.js $(node_version)'

  - task: Checkout@1
    displayName: 'Checkout source code'

  - script: |
      npm ci
      npx playwright install --with-deps
    displayName: 'Install dependencies and Playwright'

  - script: |
      npx playwright test
    displayName: 'Run Playwright Tests'

  - task: PublishPipelineArtifact@1
    condition: always()
    inputs:
      targetPath: 'playwright-report'
      artifactName: 'playwright-report'
    displayName: 'Publish HTML Report'